apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simulator-role
rules:
  - apiGroups: ["platform.study.com"]
    resources: ["simulatorinstances"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["platform.study.com"]
    resources: ["simulatorinstances/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["platform.study.com"]
    resources: ["models"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "patch"]
