apiVersion: platform.study.com/v1
kind: SimulatorInstance
metadata:
  labels:
    app.kubernetes.io/name: hello-k8s-ai
    app.kubernetes.io/managed-by: kustomize
  name: simulatorinstance-sample
spec:
  tenantRef:
    name: tenant-sample
  modelRef:
    name: model-sample
  replicas: 0
  traffic:
    qps: 0
