apiVersion: platform.study.com/v1
kind: Orchestrator
metadata:
  labels:
    app.kubernetes.io/name: hello-k8s-ai
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-sample
spec:
  tenantRef:
    name: tenant-sample
  minReplicas: 1
  maxReplicas: 0 # 0 表示不限制副本数（模拟器无网关，接受任意 QPS）
  allowScaleToZero: true
