apiVersion: platform.study.com/v1
kind: TenantNodePolicy
metadata:
  labels:
    app.kubernetes.io/name: hello-k8s-ai
    app.kubernetes.io/managed-by: kustomize
  name: tenantnodepolicy-sample
spec:
  tenantRef:
    name: tenant-sample
  nodeRef:
    name: workernode-sample
  effect: Allow
