apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- ../observability

images:
- name: hello-k8s-ai-controller
  newName: hello-k8s-ai-controller
  newTag: dev

patches:
- path: manager-observability-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: hello-k8s-ai-controller-manager
