name: E2E 测试

on:
  push:
  pull_request:

permissions: {}

jobs:
  test-e2e:
    permissions:
      contents: read
    name: Ubuntu E2E 测试
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 配置 Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: 安装最新版 Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: 验证 Kind 安装
        run: kind version

      - name: 执行 E2E 测试
        run: |
          go mod tidy
          make test-e2e
